#!/bin/bash
# Author: Venkatesh Krishnamurthy. Copyright 2022.
# This script is used to remove all the files generated by plot.py after testing
# And auto-removes itself

rm *.txt
rm *.png
rm *.mp4
rm *.m 
rm -r time_series/
rm -r cycles/
rm -r main_out/
rm -r pretty_plots/

rm plot.py
rm cleanup.sh
