#!/bin/bash
# Author: Venkatesh Krishnamurthy. Copyright 2022.
# This script is used to remove all the files generated by plot.py after testing
# And auto-removes itself
rm *.txt
rm *.png
rm *.mp4
rm -r time_series/
rm -r cycles/
rm cleanup.sh
